## ESERCIZIO
Contare il numero di classi nelle quali vi sono almeno due compagni che sono nati
lo stesso giorno

In [1]:
import numpy as np

In [2]:
classi = np.random.choice(np.arange(1, 366), size = (1000, 25))
classi

array([[181, 224, 106, ..., 316, 322, 303],
       [175, 154,  12, ..., 267, 243, 331],
       [256, 202, 291, ..., 137,  90, 178],
       ...,
       [118, 144, 317, ..., 313, 261, 342],
       [269, 161, 345, ...,  39,  86, 225],
       [355, 276, 298, ...,   4, 343, 182]])

In [3]:
classi = np.sort(classi)

In [4]:
classi

array([[ 44,  48,  63, ..., 303, 316, 322],
       [ 12,  38,  44, ..., 331, 332, 340],
       [ 25,  80,  90, ..., 302, 305, 316],
       ...,
       [ 16,  25,  67, ..., 337, 342, 360],
       [ 12,  23,  39, ..., 345, 354, 354],
       [  2,   4,  23, ..., 355, 363, 365]])

In [5]:
classi_roll = np.roll(classi, 1)
classi_roll

array([[365,  44,  48, ..., 294, 303, 316],
       [322,  12,  38, ..., 308, 331, 332],
       [340,  25,  80, ..., 291, 302, 305],
       ...,
       [360,  16,  25, ..., 317, 337, 342],
       [360,  12,  23, ..., 318, 345, 354],
       [354,   2,   4, ..., 355, 355, 363]])

In [6]:
np.count_nonzero(np.count_nonzero(classi == classi_roll, 1) >= 1)

577