### Esercizio
Dato n intero, generare l'array 2d fatto in questo modo:

    [[1, 2, 3, ..., n],
     [1, 2, 3, ..., n],
     ...
     ...
     [1, 2, 3, ..., n]

con n righe

In [1]:
import numpy as np

In [7]:
n = 4
array1d = np.arange(1, n * n + 1)
array2d = (array1d % n).reshape((n, -1))
array2d

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 2, 3, 0]], dtype=int32)

In [10]:
array2d = 1 + np.roll(array2d, 1)
array2d

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]], dtype=int32)

In [11]:
array2d.reshape(-1)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4], dtype=int32)

In [13]:
array2d.flatten() #diventa 1d

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4], dtype=int32)