In [1]:
import numpy as np

In [2]:
%%timeit
#%% comandi magici, timeit = calcola il tempo che le istruzioni impiegano ad eseguirsi
quadrati = []
for i in range(1000000):
    quadrati.append(i**2)

377 ms ± 5.93 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
%%timeit
quadrati = np.arange(0, 1000000) ** 2

3.41 ms ± 160 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### Creare gli array unidimensionali

In [4]:
#Creare array di zeri float
array_di_zeri = np.zeros(10)
array_di_zeri

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
array_di_zeri.dtype

dtype('float64')

In [6]:
#Array conversione
array_di_zeri_int = np.zeros(10, dtype = np.int8)
array_di_zeri_int

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [7]:
array_di_uni = np.ones(10)
array_di_uni

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
array_di_cinque = np.ones(10) * 5 #BROADCAST
array_di_cinque

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [9]:
array_da_lista_numeri = np.array([1, 2, 3, 4, 1000])
array_da_lista_numeri

array([   1,    2,    3,    4, 1000])

In [10]:
array_da_lista_numeri = np.array([1, 2, 3, 4, 1000, "ciao"])
array_da_lista_numeri

array(['1', '2', '3', '4', '1000', 'ciao'], dtype='<U11')

In [11]:
float_casuali = np.random.uniform(3, 5, 10) # np.random.uniform(a(incluso), b(escluso), c) -> Numero float random tra a, b, di dimensione c
float_casuali

array([3.92562745, 3.56386525, 4.06219833, 4.52077873, 3.54858399,
       3.77784879, 3.83501032, 4.6788117 , 4.24024111, 3.75720255])

In [12]:
int_casuali = np.random.randint(1, 7, 10) # np.random.randint(a(incluso), b(escluso, c) -> Numero int random tra a, b, di dimensione c
int_casuali

array([3, 5, 5, 4, 3, 6, 3, 5, 6, 1])

In [13]:
alice = np.random.randint(1, 7, 10)
bebo = np.random.randint(1, 7, 10)

In [14]:
print(f"Lanci del dado di alice {alice}")
print(f"Lanci del dado di bebo {bebo}")

Lanci del dado di alice [1 1 4 6 4 6 1 5 1 3]
Lanci del dado di bebo [1 6 1 3 4 5 1 1 4 4]


In [15]:
alice > bebo

array([False, False,  True,  True, False,  True, False,  True, False,
       False])

In [16]:
print(f"Alice batte Bebo {np.count_nonzero(alice > bebo)} volte")

Alice batte Bebo 4 volte


In [17]:
vittorie_alice = alice > bebo

In [18]:
vittorie_alice

array([False, False,  True,  True, False,  True, False,  True, False,
       False])

In [19]:
vittorie_alice.dtype

dtype('bool')

In [20]:
array_di_interi = np.arange(4, 10)
array_di_interi

array([4, 5, 6, 7, 8, 9])

In [21]:
quadrati = np.arange(1, 11) ** 2
quadrati

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [22]:
array1 = np.arange(1, 5)
array1

array([1, 2, 3, 4])

In [23]:
len(array1)

4

In [24]:
array1.shape   #(n,) n elementi, unidimensionale

(4,)

In [25]:
array2 = np.ones(4)
array2

array([1., 1., 1., 1.])

In [26]:
array1.dtype

dtype('int32')

In [27]:
array2.dtype

dtype('float64')

In [28]:
somma = array1 + array2
somma

array([2., 3., 4., 5.])

## Creazione di array 1D
array di zeri:

    np.zeros()
    
array di uni:

    np.ones()

array da liste:
    
    np.array()
    
array di interi crescenti:

    np.arange()
    
array pseudocasuali:

    np.randint()
    np.uniform()

## ALTRE FUNZIONI UTILI DI NUMPY

    np.random.choice([value list], size)  #Array di una certa size tra i valori della lista

    np.sum(array)    #E' possibile inserire delle condizioni sulla somma
    
    np.where()       #Trova l'indice di un certo elemento

## Array pseudo-casuali

In [29]:
np.random.randint(1, 3, 10)

array([1, 2, 2, 2, 2, 1, 1, 2, 2, 2])

In [30]:
np.random.uniform(0, 1, 10)

array([0.20053569, 0.69489014, 0.3907766 , 0.82283487, 0.55687224,
       0.92144312, 0.03106081, 0.49461377, 0.26607932, 0.51884718])

In [31]:
np.random.normal(175, 12, 10)    #random.normal(media, deviazione standard, n elementi)  

array([174.58143665, 189.28391979, 185.10185614, 175.685652  ,
       178.69966685, 173.26575556, 193.47667925, 180.62463456,
       173.21999474, 169.12683781])

In [32]:
altezze = np.random.normal(175, 2, 20)
altezze

array([173.16057466, 174.88185571, 176.26466985, 178.94788201,
       175.34434077, 171.35151621, 171.80314182, 175.88359181,
       177.16242518, 175.0469715 , 172.2379789 , 175.47510371,
       172.71926308, 174.84947323, 176.79157768, 177.13675307,
       177.31208961, 172.34779586, 175.31158137, 176.19799276])

In [33]:
np.mean(altezze)    #mean(valori) = return Media

175.01132894025966

In [34]:
np.std(altezze)    #std(valori) = return Deviazione standard

2.054939798061566

## Indicizzazione per booleani
#### Una delle funzioni più potenti di numpy

In [35]:
lanci_dadi = np.random.randint(1, 7, 10)
lanci_dadi

array([5, 4, 4, 1, 3, 4, 3, 2, 1, 4])

quali sono i lanci in cui il valore del dado era > 3?

In [36]:
lanci_gt_3 = lanci_dadi > 3
lanci_gt_3

array([ True,  True,  True, False, False,  True, False, False, False,
        True])

In [37]:
lanci_dadi[lanci_gt_3]   #Indicizzo array con array di booleani -> filtra i valori solo > 3

array([5, 4, 4, 4, 4])

In [38]:
nomi = np.array(["Alice", "Bob", "Trudy"])
voti = np.array([7, 9, 2])

quali alunni sono sufficienti?

In [39]:
nomi[voti >= 6]

array(['Alice', 'Bob'], dtype='<U5')

### Array bidimensionali - 2d
Es: 
- un'immagine in scale di grigi
- un'immagine RGB a colori è costituita da 3 array 2d
- un'immagine RGBA a colori è costituita da 4 array 2d
- i dati in forma di tabella

In [43]:
matrice_di_zeri = np.zeros((3,6))    #(n1, n2) : n1 = n di array(righe), n2 = n.elementi(colonne)
matrice_di_zeri 

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [44]:
matrice_di_zeri.shape

(3, 6)

In [45]:
array1d_di_zeri = np.zeros(7)
array1d_di_zeri

array([0., 0., 0., 0., 0., 0., 0.])

In [46]:
array1d_di_zeri.shape

(7,)

In [47]:
np.ones((10, 8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [48]:
np.ones((10, 8), dtype = np.int8)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=int8)

In [50]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
np.array([[1, 2, 3], [4, 5, "ciao"]])

array([['1', '2', '3'],
       ['4', '5', 'ciao']], dtype='<U11')

In [55]:
np.random.randint(1, 7, (10, 2))

array([[5, 5],
       [5, 2],
       [5, 6],
       [2, 4],
       [1, 1],
       [2, 6],
       [2, 1],
       [1, 2],
       [5, 5],
       [5, 6]])

In [56]:
np.random.uniform(0, 1, (4, 4))

array([[0.57880284, 0.72650106, 0.88826224, 0.4464077 ],
       [0.27101715, 0.15216795, 0.35284203, 0.37985287],
       [0.67072533, 0.26389365, 0.84305022, 0.7280351 ],
       [0.08324479, 0.63573903, 0.69422184, 0.83130843]])

In [57]:
array_3d = np.random.uniform(0, 1, (3, 3, 2))
array_3d

array([[[0.56388253, 0.92993508],
        [0.59695542, 0.4747752 ],
        [0.37352128, 0.34420341]],

       [[0.34754942, 0.28108518],
        [0.44889887, 0.23359609],
        [0.9492387 , 0.4277472 ]],

       [[0.92051092, 0.98318054],
        [0.82520723, 0.90409157],
        [0.13079248, 0.11368575]]])

In [58]:
array_3d.shape

(3, 3, 2)

### Operazioni matematiche di aggregazione
Per esempio:
- somma
- massimo / minimo
- media
- deviazione standard
- somma cumulata

In [63]:
#somma
array = np.arange(1, 101)
np.sum(array)

5050

In [68]:
#massimo / minimo
array = np.random.uniform(0, 1, 10)
print(array)

[0.36210231 0.55201518 0.79536024 0.67368856 0.03332127 0.82569156
 0.61092548 0.20920634 0.43624132 0.15134202]


In [69]:
np.max(array) # massimo

0.8256915624855705

In [70]:
# deviazione standard
np.std(array)

0.2594660555850418

In [72]:
array_di_uni = np.ones(10)
array_di_uni

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [73]:
np.sum(array_di_uni)

10.0

In [74]:
np.cumsum(array_di_uni) #somma cumulata

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [75]:
prezzo_apple = 178
variazioni = np.array([8, 3, -20, 6])

In [78]:
prezzo_apple + np.cumsum(variazioni)

array([186, 189, 169, 175])

### Cambiare forma agli array
funzioni : 
    
    np.roll(array, n)  # shiftato di n avanti

In [80]:
array_1d = np.arange(1, 13)
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [81]:
array_1d.reshape((4, 3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [82]:
array_1d.reshape((6, 2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [83]:
array_1d.reshape((3, -1))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Slicing

In [84]:
array1d = np.arange(1, 11)
array1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
array1d[3]

4

In [87]:
array1d[3 : 8]

array([4, 5, 6, 7, 8])

In [88]:
array1d[-1]

10

In [89]:
array1d[-2]

9

In [90]:
array1d[1: -1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
array1d[: : -1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [92]:
array1d[3: 8: 2]

array([4, 6, 8])

In [93]:
np.random.seed(10)   #blocca il seme
array2d = np.random.uniform(0 , 1, (3, 3))
array2d

array([[0.77132064, 0.02075195, 0.63364823],
       [0.74880388, 0.49850701, 0.22479665],
       [0.19806286, 0.76053071, 0.16911084]])

In [94]:
array2d[0, 0]

0.771320643266746

In [95]:
array2d[1, 2]

0.22479664553084766

In [96]:
array2d[1: ]

array([[0.74880388, 0.49850701, 0.22479665],
       [0.19806286, 0.76053071, 0.16911084]])

In [97]:
array2d[:, 1:]

array([[0.02075195, 0.63364823],
       [0.49850701, 0.22479665],
       [0.76053071, 0.16911084]])

In [98]:
array2d[1:, 1:]

array([[0.49850701, 0.22479665],
       [0.76053071, 0.16911084]])

In [100]:
array2d[1:, 1:] = 0   #punta sempre all'array originale, i valori cambiano sull'array originale
array2d

array([[0.77132064, 0.02075195, 0.63364823],
       [0.74880388, 0.        , 0.        ],
       [0.19806286, 0.        , 0.        ]])