In [1]:
import numpy as np

In [2]:
alice = np.random.randint(1, 7, 10)
bob = np.random.randint(1, 7, 10)

In [3]:
alice

array([5, 2, 2, 1, 6, 1, 6, 3, 2, 1])

In [4]:
bob

array([5, 5, 3, 6, 4, 4, 3, 1, 6, 5])

In [5]:
alice[alice > bob]

array([6, 6, 3])