# Esercizio
Scacchiera: 
size
input lato (deve essere multiplo di size)
Prima sfumare tutto la scacchiera e poi aggiungere i quadratini neri

In [102]:
import numpy as np
import matplotlib.pyplot as plt

In [144]:
size = 100
side = 10

In [167]:
chessboard = np.zeros((size, size), dtype = "int16")

In [168]:
chessboard

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int16)

In [169]:
#chessboard[ : ] = np.arange(0, size)

In [170]:
chessboard[0 : : 2, 0 : : 2] = 1
chessboard[1 : : 2, 1 : : 2] = 1

In [171]:
chessboard

array([[1, 0, 1, ..., 0, 1, 0],
       [0, 1, 0, ..., 1, 0, 1],
       [1, 0, 1, ..., 0, 1, 0],
       ...,
       [0, 1, 0, ..., 1, 0, 1],
       [1, 0, 1, ..., 0, 1, 0],
       [0, 1, 0, ..., 1, 0, 1]], dtype=int16)

In [173]:
indexes = np.zeros((size, size), dtype = "int16")
indexes[ : , : ] = np.arange(0, size)

In [183]:
indexes[chessboard == 1]

array([ 0,  2,  4, ..., 95, 97, 99], dtype=int16)