### Esercizio
Dato v = np.array([1 , 2 , 3, 1, -2, 4, 3, 1, 2])

Trovare massimi e minimi, locali e globali sfruttando np.roll()

In [1]:
import numpy as np

In [2]:
vettore = np.array([1 , 2 , 3, 1, -2, 4, 3, 1, 2])

In [3]:
vettore

array([ 1,  2,  3,  1, -2,  4,  3,  1,  2])

In [4]:
massimo_globale = np.max(vettore)
massimo_globale

4

In [5]:
minimo_globale = np.min(vettore)
minimo_globale

-2

In [6]:
vettore_dx = np.roll(vettore, 1)
vettore_dx

array([ 2,  1,  2,  3,  1, -2,  4,  3,  1])

In [7]:
vettore_sx = np.roll(vettore, -1)
vettore_sx

array([ 2,  3,  1, -2,  4,  3,  1,  2,  1])

In [8]:
massimo_locale = vettore[(vettore > vettore_sx) & (vettore > vettore_dx)]
massimo_locale

array([3, 4, 2])

In [9]:
minimo_locale = vettore[(vettore < vettore_sx) & (vettore < vettore_dx)]
minimo_locale

array([ 1, -2,  1])