In [31]:
import numpy as np

In [32]:
array = np.array([0, 4, 5, 6, 1, 2, 3, 8, 9, 5])

In [33]:
array

array([0, 4, 5, 6, 1, 2, 3, 8, 9, 5])

In [34]:
position_sx_1 = np.roll(array, -1)
position_sx_2 = np.roll(array, -2)

In [42]:
seq = (array == 1) & (position_sx_1 == 2) & (position_sx_2 == 3)
seq

array([False, False, False, False,  True, False, False, False, False,
       False])

In [43]:
indici = np.arange(0, len(array))
indici

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
indici[seq]

array([4])