### Esercizio
Diecimila partite - mille lanci per partita - 55% per cento di croce?

In [2]:
import numpy as np

In [5]:
N_MATCH = 10000
N_FLIPS = 1000

In [6]:
faces = np.array(["testa", "croce"])

In [30]:
flips_matches = np.random.choice(faces, (N_MATCH, N_FLIPS))
flips_matches

array([['testa', 'testa', 'testa', ..., 'testa', 'testa', 'testa'],
       ['croce', 'croce', 'croce', ..., 'croce', 'testa', 'croce'],
       ['croce', 'testa', 'croce', ..., 'croce', 'testa', 'croce'],
       ...,
       ['croce', 'croce', 'testa', ..., 'testa', 'testa', 'croce'],
       ['testa', 'testa', 'testa', ..., 'croce', 'testa', 'testa'],
       ['croce', 'croce', 'croce', ..., 'croce', 'testa', 'croce']],
      dtype='<U5')

In [44]:
number_of_match_croce_tg55 = 0
for match_counter in range(len(flips_matches)):
    number_of_croce = np.count_nonzero(flips_matches[match_counter] == "croce")
    number_of_testa = np.count_nonzero(flips_matches[match_counter] == "testa")
    percentage_of_croce = number_of_croce * 100 / N_FLIPS
    if percentage_of_croce >= 55:
        number_of_match_croce_tg55 += 1

In [47]:
print(f"In {number_of_match_croce_tg55} partite il 55% dei {N_FLIPS} è croce")

In 12 partite il 55% dei 1000 è croce


# ----------

In [3]:
vett = np.zeros((4, 5))
vett[:] = np.arange(0, 5)
vett

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [4]:
np.sum(vett)

40.0

In [6]:
np.sum(vett, axis = 0)

array([ 0.,  4.,  8., 12., 16.])

In [5]:
np.sum(vett, axis = 1)

array([10., 10., 10., 10.])

In [7]:
np.max(vett)

4.0

In [8]:
np.max(vett, axis = 0)

array([0., 1., 2., 3., 4.])

In [9]:
np.max(vett, axis = 1)

array([4., 4., 4., 4.])