### Esercizio
array sulla media delle altezze dei compagni di classe

In [1]:
import numpy as np

In [2]:
altezze = np.random.uniform(160, 200, 20)
media = np.mean(altezze)
deviazione_standard = np.std(altezze)

In [3]:
altezze_normal = np.random.normal(media, deviazione_standard, 20)

In [4]:
altezze

array([166.75607447, 183.31625946, 182.36069638, 197.30250706,
       195.75595043, 179.52380925, 190.23197594, 192.10728084,
       170.31725175, 176.58121883, 173.2547206 , 183.18694933,
       162.19154013, 197.48398746, 180.14780648, 174.8039685 ,
       180.2275853 , 183.89494093, 175.67915852, 160.19823819])

In [5]:
altezze_normal

array([163.34266894, 177.85915715, 185.44657222, 202.41227745,
       174.71769576, 180.15186499, 166.56104739, 174.49489143,
       187.73460569, 175.87488883, 184.14252272, 168.61741868,
       197.71673392, 200.06405296, 155.55394106, 192.70206061,
       166.92070779, 172.60687213, 186.60144919, 176.84472529])

In [6]:
altezze_normal > 200

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False])

In [7]:
np.count_nonzero(altezze_normal > 200)

2

In [8]:
altezze_normal[altezze_normal > 200]

array([202.41227745, 200.06405296])